# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cf9ff085e3eff2bbb5b4984c030dbdad55831bc1f58c8e16aec2c0a90b9179090a0788806a55c6dd7780072d7627adaf1cf86607ed33786e91abf5d49684655

test:
  secret_key_base: cb6cd862b9e24312440e27610f890001d466fe444cb1efe06006fe2d409044dbba730a1dd226fa9b2c2da895ee0037f9079e98f5ab752660a866c827ee661720

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
